# Generated by Django 6.0.5 on 2026-06-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_orden', models.CharField(choices=[('Arresto', 'Arresto'), ('Allanamiento', 'Allanamiento'), ('Comparecencia', 'Comparecencia')], max_length=50)),
                ('juez_emisor', models.CharField(max_length=150)),
                ('tribunal', models.CharField(max_length=150)),
                ('cargos', models.TextField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('sospechoso_nombre', models.CharField(help_text='Nombre o alias del sospechoso', max_length=150)),
                ('sospechoso_identificacion', models.CharField(blank=True, help_text='ID o placa vinculada', max_length=100, null=True)),
                ('expediente_vinculado', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='ordenes_judiciales/pdfs/')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Expirada', 'Expirada'), ('Ejecutada', 'Ejecutada')], default='Activa', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ejecucion', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('oficial_ejecutor', models.CharField(max_length=150)),
                ('resultado', models.CharField(choices=[('Exitosa', 'Exitosa'), ('Fallida', 'Fallida')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='ordenes_judiciales.ordenjudicial')),
            ],
        ),
    ]
