/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-container": "#d0e1fb",
        "tertiary-fixed": "#d8e3fb",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "primary-container": "#0b2b5e",
        "on-background": "#191c1e",
        "on-surface-variant": "#44474f",
        "secondary": "#505f76",
        "primary-fixed-dim": "#aec6ff",
        "on-primary-container": "#7b94cd",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline-variant": "#c4c6d1",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "on-secondary-container": "#54647a",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#2b467a",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-primary": "#aec6ff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#0b1c30",
        "surface-container": "#eceef0",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#3c475a",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d3e4fe",
        "on-primary": "#ffffff",
        "primary": "#00173d",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-container": "#8994aa",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#bcc7de",
        "on-tertiary": "#ffffff",
        "outline": "#747780",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#001a43",
        "tertiary-container": "#222d3f",
        "tertiary": "#0d182a",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#2d3133",
        "surface-tint": "#445d93",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "xl": "32px",
        "sidebar-width": "260px",
        "gutter": "1.5rem",
        "base": "4px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "data-mono": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
