services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: safecity_clickhouse_demo
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password12345
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: always
