# Generated by Django 6.0.5 on 2026-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
    ]
