# Generated by Django 6.0.5 on 2026-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial', models.IntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('Amonestacion', 'Amonestación'), ('Felicitacion', 'Felicitación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('id_comandante', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rrhh_amonestacion',
            },
        ),
        migrations.CreateModel(
            name='AsignacionCuadrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial', models.IntegerField(db_index=True)),
                ('id_cuadrante', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('timestamp_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rrhh_asignacion_cuadrante',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial', models.IntegerField(db_index=True)),
                ('timestamp_entrada', models.DateTimeField(auto_now_add=True)),
                ('timestamp_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rrhh_asistencia_registro',
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial', models.IntegerField(db_index=True)),
                ('nombre_curso', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_completado', models.DateField()),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rrhh_certificacion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial', models.IntegerField(db_index=True)),
                ('tipo_permiso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('id_comandante_aprobador', models.IntegerField(blank=True, null=True)),
                ('timestamp_solicitud', models.DateTimeField(auto_now_add=True)),
                ('timestamp_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rrhh_solicitud_permiso',
            },
        ),
    ]
