# Generated by Django 6.0.5 on 2026-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo_rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollCallBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_supervisor', models.IntegerField(db_index=True)),
                ('bolo_details', models.TextField(blank=True, null=True)),
                ('special_assignments', models.TextField(blank=True, null=True)),
                ('asistentes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rrhh_roll_call_briefing',
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial_saliente', models.IntegerField(db_index=True)),
                ('id_oficial_entrante', models.IntegerField(db_index=True)),
                ('checklist_detenidos', models.BooleanField(default=False)),
                ('checklist_equipos', models.BooleanField(default=False)),
                ('checklist_incidentes', models.BooleanField(default=False)),
                ('novedades', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rrhh_shift_handover',
            },
        ),
    ]
