# Generated by Django 5.0.6 on 2026-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo_rrhh', '0003_alter_amonestacion_id_alter_asignacioncuadrante_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='documento_respaldo',
            field=models.FileField(blank=True, null=True, upload_to='rrhh/permisos/'),
        ),
    ]
