# Generated by Django 6.0.5 on 2026-08-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuejaCiudadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudadano', models.CharField(max_length=150)),
                ('contacto_ciudadano', models.CharField(max_length=150)),
                ('id_oficial_implicado', models.IntegerField(help_text='ID ClickHouse del oficial')),
                ('fecha_incidente', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Recibida', 'Recibida'), ('En Investigacion', 'En Investigación'), ('Resuelta', 'Resuelta'), ('Desestimada', 'Desestimada')], default='Recibida', max_length=50)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReunionComunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadrante_distrito', models.CharField(max_length=50)),
                ('fecha_reunion', models.DateField()),
                ('cantidad_asistentes', models.IntegerField()),
                ('temas_tratados', models.TextField()),
                ('compromisos', models.TextField(blank=True, null=True)),
                ('oficial_responsable', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoDeFuerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficial', models.IntegerField(help_text='ID ClickHouse del oficial')),
                ('id_incidente', models.CharField(blank=True, help_text='Case Number opcional', max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_fuerza', models.CharField(choices=[('Fisica No Letal', 'Física No Letal'), ('Arma Electrica (Taser)', 'Arma Eléctrica (Taser)'), ('Arma Quimica (Gas)', 'Arma Química (Gas)'), ('Arma de Fuego (Letal)', 'Arma de Fuego (Letal)')], max_length=50)),
                ('justificacion_legal', models.TextField()),
                ('hubo_heridos', models.BooleanField(default=False)),
                ('reporte_medico_url', models.FileField(blank=True, null=True, upload_to='comunidad/fuerza/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
