# Generated by Django 6.0.5 on 2026-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia_comunitaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejaciudadana',
            name='id_oficial_implicado',
            field=models.IntegerField(blank=True, help_text='ID ClickHouse del oficial', null=True),
        ),
    ]
